
# Resource directory
RES_DIR=../app/src/main/res

icons: icon_ic_launcher icon_ic_mail icon_ic_notif_mail

icon_ic_launcher:
	rsvg-convert -w 192 -h 192 ic_launcher.svg -o ${RES_DIR}/drawable-xxxhdpi/ic_launcher.png
	rsvg-convert -w 144 -h 144 ic_launcher.svg -o ${RES_DIR}/drawable-xxhdpi/ic_launcher.png
	rsvg-convert -w 96  -h 96  ic_launcher.svg -o ${RES_DIR}/drawable-xhdpi/ic_launcher.png
	rsvg-convert -w 72  -h 72  ic_launcher.svg -o ${RES_DIR}/drawable-hdpi/ic_launcher.png
	rsvg-convert -w 48  -h 48  ic_launcher.svg -o ${RES_DIR}/drawable-mdpi/ic_launcher.png

icon_ic_mail:
	rsvg-convert -w 192 -h 192 ic_mail.svg -o ${RES_DIR}/drawable-xxxhdpi/ic_mail.png
	rsvg-convert -w 144 -h 144 ic_mail.svg -o ${RES_DIR}/drawable-xxhdpi/ic_mail.png
	rsvg-convert -w 96  -h 96  ic_mail.svg -o ${RES_DIR}/drawable-xhdpi/ic_mail.png
	rsvg-convert -w 72  -h 72  ic_mail.svg -o ${RES_DIR}/drawable-hdpi/ic_mail.png
	rsvg-convert -w 48  -h 48  ic_mail.svg -o ${RES_DIR}/drawable-mdpi/ic_mail.png

icon_ic_notif_mail:
	rsvg-convert -w 88 -h 88 ic_notif_mail.svg -o ${RES_DIR}/drawable-xxxhdpi/ic_notif_mail.png
	rsvg-convert -w 66 -h 66 ic_notif_mail.svg -o ${RES_DIR}/drawable-xxhdpi/ic_notif_mail.png
	rsvg-convert -w 44 -h 44 ic_notif_mail.svg -o ${RES_DIR}/drawable-xhdpi/ic_notif_mail.png
	rsvg-convert -w 33 -h 33 ic_notif_mail.svg -o ${RES_DIR}/drawable-hdpi/ic_notif_mail.png
	rsvg-convert -w 22 -h 22 ic_notif_mail.svg -o ${RES_DIR}/drawable-mdpi/ic_notif_mail.png
